In [9]:
import numpy as np

# 1a)


print("a)\n")



X = {'A', 'B'}

A = {'P', 'RA', 'RB'}

Z = {'A', 'B', 'N'}


print("X: %s" % X)
print("A: %s" % A)



# 1b)

print("\nb)\n")



PRB = PRA = np.array([
    [0.5, 0.5],
    [0.5, 0.5]
])

PP = np.array([
    [1, 0],
    [0, 1]
])

ORA = ORB = np.array([
    [0, 0, 1],
    [0, 0, 1]
])


OP = np.array([
    [0.9, 0.1, 0],
    [0.1, 0.9, 0]
])


C = np.array([
    [0, 1, 0.1],
    [1, 0, 0.1]
])



print("PRB = PRA =\n%s" % PRA)

print("\nPP =\n%s" % PP)

print("\nORA= ORB =\n%s" % ORA)

print("\nOP =\n%s" % OP)

print("\nC=\n%s" % C)


# 1c)

print("\nc)\n")


alpha = np.array([
    [0.7, 0.3]
])

âlpha = np.matmul(alpha, PP)

newAlpha = np.matmul(âlpha, np.diag(OP[:, 1]))

suma = sum(newAlpha[0])

newAlpha[0][0] = newAlpha[0][0] / suma
newAlpha[0][1] = newAlpha[0][1] / suma

print("Belief = %s" % newAlpha[0])

a)

X: {'B', 'A'}
A: {'P', 'RB', 'RA'}

b)

PRB = PRA =
[[ 0.5  0.5]
 [ 0.5  0.5]]

PP =
[[1 0]
 [0 1]]

ORA= ORB =
[[0 0 1]
 [0 0 1]]

OP =
[[ 0.9  0.1  0. ]
 [ 0.1  0.9  0. ]]

C=
[[ 0.   1.   0.1]
 [ 1.   0.   0.1]]

c)

Belief = [ 0.20588235  0.79411765]
