# Learning and Decision Making

## Laboratory 3: Markov decision problems

In the end of the lab, you should submit all code/answers written in the tasks marked as "Activity n. XXX", together with the corresponding outputs and any replies to specific questions posed to the e-mail <adi.tecnico@gmail.com>. Make sure that the subject is of the form [&lt;group n.&gt;] LAB &lt;lab n.&gt;.

### 1. Modeling

Consider once again the knight domain described in the Homework and which you described as a Markov decision process.

<img src="knight.png" width="200px">

Recall that:

* At each step, the knight may move in any of the four directions---up, down, left and right. 

* The movement succeeds with a 0.6 probability and fails with a 0.4 probability. When the movement fails, the knight may stay in the same cell or move to one of the immediately adjacent cells (if there is one) with equal probability.

* The goal of the knight is to save (reach) the princess and avoid the dragon.

**Throughout the lab, use $\gamma=0.99$.**

---

#### Activity 1.        

Implement your Markov decision process in Python. In particular,

* Create a list with all the states;
* Create a list with all the actions;
* For each action, define a `numpy` array with the corresponding transition probabilities;
* Define a `numpy`array with the costs. Make sure that:
    * The costs lie in the interval [0, 1]
    * The cost for standing in the princess's cell is minimal
    * The cost for standing in the dragon's cell is maximal
    * The costs for the intermediate cells are around 1/5 of those of standing in the dragon's cell

The order for the states and actions used in the transition probability and cost matrices should match that in the lists of states and actions. 

**Note**: Don't forget to import `numpy`.

---

In [1]:
import numpy as np

X = {1, 2, 3, 4, 5, 6}

A = {"U", "D", "L", "R"}

print("X:", X)
print("A: %s\n" % (A))


PU = np.array([
    [0.8, 0.1, 0, 0.1, 0, 0],
    [0.1, 0.7, 0.1, 0, 0.1, 0],
    [0, 0.1, 0.8, 0, 0, 0.1],
    [0.6, 0, 0, 0.3, 0.1, 0],
    [0, 0.6, 0, 0.1, 0.2, 0.1],
    [0, 0, 0.6, 0, 0.1, 0.3]
])

PD = np.array([
    [0.3, 0.1, 0, 0.6, 0, 0],
    [0.1, 0.2, 0.1, 0, 0.6, 0],
    [0, 0.1, 0.3, 0, 0, 0.6],
    [0.1, 0, 0, 0.8, 0.1, 0],
    [0, 0.1, 0, 0.1, 0.7, 0.1],
    [0, 0, 0.1, 0, 0.1, 0.8]
])

PL = np.array([
    [0.8, 0.1, 0, 0.1, 0, 0],
    [0.6, 0.2, 0.1, 0, 0.1, 0],
    [0, 0.6, 0.3, 0, 0, 0.1],
    [0.1, 0, 0, 0.8, 0.1, 0],
    [0, 0.1, 0, 0.6, 0.2, 0.1],
    [0, 0, 0.1, 0, 0.6, 0.3]
])

PR = np.array([
    [0.3, 0.6, 0, 0.1, 0, 0],
    [0.1, 0.2, 0.6, 0, 0.1, 0],
    [0, 0.1, 0.8, 0, 0, 0.1],
    [0.1, 0, 0, 0.3, 0.6, 0],
    [0, 0.1, 0, 0.1, 0.2, 0.6],
    [0, 0, 0.1, 0, 0.1, 0.8]
])

print("PU=")
print(PU)
print("\nPD=")
print(PD)
print("\nPL=")
print(PL)
print("\nPR=")
print(PR)


C = np.array([
    [.2, .2, .2, .2],
    [.2, .2, .2, .2],
    [.2, .2, .2, .2],
    [.2, .2, .2, .2],
    [1, 1, 1, 1],
    [0, 0, 0, 0]
])

print("\nC=\n%s" % C)


X: {1, 2, 3, 4, 5, 6}
A: {'R', 'D', 'L', 'U'}

PU=
[[ 0.8  0.1  0.   0.1  0.   0. ]
 [ 0.1  0.7  0.1  0.   0.1  0. ]
 [ 0.   0.1  0.8  0.   0.   0.1]
 [ 0.6  0.   0.   0.3  0.1  0. ]
 [ 0.   0.6  0.   0.1  0.2  0.1]
 [ 0.   0.   0.6  0.   0.1  0.3]]

PD=
[[ 0.3  0.1  0.   0.6  0.   0. ]
 [ 0.1  0.2  0.1  0.   0.6  0. ]
 [ 0.   0.1  0.3  0.   0.   0.6]
 [ 0.1  0.   0.   0.8  0.1  0. ]
 [ 0.   0.1  0.   0.1  0.7  0.1]
 [ 0.   0.   0.1  0.   0.1  0.8]]

PL=
[[ 0.8  0.1  0.   0.1  0.   0. ]
 [ 0.6  0.2  0.1  0.   0.1  0. ]
 [ 0.   0.6  0.3  0.   0.   0.1]
 [ 0.1  0.   0.   0.8  0.1  0. ]
 [ 0.   0.1  0.   0.6  0.2  0.1]
 [ 0.   0.   0.1  0.   0.6  0.3]]

PR=
[[ 0.3  0.6  0.   0.1  0.   0. ]
 [ 0.1  0.2  0.6  0.   0.1  0. ]
 [ 0.   0.1  0.8  0.   0.   0.1]
 [ 0.1  0.   0.   0.3  0.6  0. ]
 [ 0.   0.1  0.   0.1  0.2  0.6]
 [ 0.   0.   0.1  0.   0.1  0.8]]

C=
[[ 0.2  0.2  0.2  0.2]
 [ 0.2  0.2  0.2  0.2]
 [ 0.2  0.2  0.2  0.2]
 [ 0.2  0.2  0.2  0.2]
 [ 1.   1.   1.   1. ]
 [ 0.   0.   0.   0

### 2. Prediction

You are now going to evaluate a given policy, computing the corresponding cost-to-go.

---

#### Activity 2.

Describe the policy that, in each state $x$, always moves the knight to the cell closest to the princess (irrespectively of the dragon). If multiple such cells exist, the knight should select randomly between the two.

For example, suppose that the knight is in cell 1. The knight should then select randomly between the actions _D_ and _R_. Conversely, suppose that the knight is in cell 4. The knight should then select actions _R_ with probability 1.

**Note:** The policy should be described as a vector with as many rows as there are states and as many columns as there are actions, where the entry _xa_ has the probability of selecting action _a_ in state _x_.

---

In [2]:
Policy = np.array([
    [0., 0.5, 0., 0.5],
    [0., 0.5, 0., 0.5],
    [0., 1., 0., 0.],
    [0., 0., 0., 1.],
    [0., 0., 0., 1.],
    [0., 0.5, 0., 0.5]
])

print("\nPolicy=\n%s" % Policy)


Policy=
[[ 0.   0.5  0.   0.5]
 [ 0.   0.5  0.   0.5]
 [ 0.   1.   0.   0. ]
 [ 0.   0.   0.   1. ]
 [ 0.   0.   0.   1. ]
 [ 0.   0.5  0.   0.5]]


---

#### Activity 3.

Compute the cost-to-go function $J^\pi$ associated with the policy from Activity 2.

---

In [3]:
Ppi = Policy[:, 0, None]*PU + Policy[:, 1, None]*PD + Policy[:, 2, None]*PL + Policy[:, 3, None]*PR

Cpi = (Policy * C).sum(axis=1)

print("Ppi=\n%s" % Ppi)

print("\nCpi=%s" % Cpi)

I = np.identity(6)
gama = 0.99

Jpi = np.matmul(np.linalg.inv(I - gama * Ppi), Cpi)

print("\nJpi=%s" % Jpi)

Ppi=
[[ 0.3   0.35  0.    0.35  0.    0.  ]
 [ 0.1   0.2   0.35  0.    0.35  0.  ]
 [ 0.    0.1   0.3   0.    0.    0.6 ]
 [ 0.1   0.    0.    0.3   0.6   0.  ]
 [ 0.    0.1   0.    0.1   0.2   0.6 ]
 [ 0.    0.    0.1   0.    0.1   0.8 ]]

Cpi=[ 0.2  0.2  0.2  0.2  1.   0. ]

Jpi=[ 16.26056701  15.95826371  15.28584405  16.45495016  16.42766638
  15.09441121]


### 3. Control

In this section you are going to compare value and policy iteration, both in terms of time and number of iterations.

---

#### Activity 4

Show that the policy in Activity 3 is _not_ optimal: use value iteration to compute $J^*$ and show that $J^*\neq J^\pi$. Track the time and the number of iterations taken to compute $J^*$.

**Note 1:** Stop the algorithm when the error between iterations is smaller than $10^{-8}$.

**Note 2:** You may find useful the function ``time()`` from the module ``time``.

---

In [5]:
import time

cu = C[:, 0, None]
cd = C[:, 1, None]
cl = C[:, 2, None]
cr = C[:, 3, None]


J = np.zeros((6, 1))
err = 1
i = 0
gama = 0.99
start = time.time()

while err > 1e-8:
    Qu = cu + gama * PU.dot(J)
    Qd = cd + gama * PD.dot(J)
    Ql = cl + gama * PL.dot(J)
    Qr = cr + gama * PR.dot(J)
    Jnew = np.min((Qu, Qd, Ql, Qr), axis=0)
    err = np.linalg.norm(Jnew - J)
    i += 1
    J = Jnew

end = time.time()
t = end - start

print("time elapsed = %s" % t)
print("iterations = %s\n" % i)
print(J)

time elapsed = 0.13509035110473633
iterations = 1726

[[ 14.06797074]
 [ 13.93809867]
 [ 13.67954678]
 [ 14.24800834]
 [ 14.74722471]
 [ 13.53004987]]


---

#### Activity 5

Compute once again the optimal policy now using policy iteration. Track the time and number of iterations taken and compare to those of Activity 4.

**Note:** If you find that numerical errors affect your computations (especially when comparing two values/arrays) you may use the `numpy` function `isclose` with adequately set absolute and relative tolerance parameters (e.g., $10^{-8}$).

---

In [ ]:
# Insert your code here

### 4. Simulation

Finally, in this section you will check whether the theoretical computations of the cost-to-go actually correspond to the cost incurred by an agent following a policy.

---

#### Activity 6

Starting both in cell 1 and cell 5 in the figure, 

* Generate **100** trajectories of 10,000 steps each, following the optimal policy for the MDP. 
* For each trajectory, compute the accumulated (discounted) cost. 
* Compute the average cost over the 100 trajectories.
* Compare the resulting value with that computed in Activity 4 for the two states. 

** Note:** The simulation may take a bit of time, don't despair ☺️.

---

In [ ]:
# Insert your code here