In [25]:
import numpy as np

# 1a)

print("1a)\n")

# U - Up
# D - Down
# L - Left
# R - Right

X = {1, 2, 3, 4, 5, 6}

A = {"U", "D", "L", "R"}

print("X:", X)
print("A: %s\n" % (A))


# 1b)

print("1b)\n")

PU = np.array([
    [0.8, 0.1, 0, 0.1, 0, 0],
    [0.1, 0.7, 0.1, 0, 0.1, 0],
    [0, 0.1, 0.8, 0, 0, 0.1],
    [0.6, 0, 0, 0.3, 0.1, 0],
    [0, 0.6, 0, 0.1, 0.2, 0.1],
    [0, 0, 0.6, 0, 0.1, 0.3]
])

PD = np.array([
    [0.3, 0.1, 0, 0.6, 0, 0],
    [0.1, 0.2, 0.1, 0, 0.6, 0],
    [0, 0.1, 0.3, 0, 0, 0.6],
    [0.1, 0, 0, 0.8, 0.1, 0],
    [0, 0.1, 0, 0.1, 0.7, 0.1],
    [0, 0, 0.1, 0, 0.1, 0.8]
])

PL = np.array([
    [0.8, 0.1, 0, 0.1, 0, 0],
    [0.6, 0.2, 0.1, 0, 0.1, 0],
    [0, 0.6, 0.3, 0, 0, 0.1],
    [0.1, 0, 0, 0.8, 0.1, 0],
    [0, 0.1, 0, 0.6, 0.2, 0.1],
    [0, 0, 0.1, 0, 0.6, 0.3]
])

PR = np.array([
    [0.3, 0.6, 0, 0.1, 0, 0],
    [0.1, 0.2, 0.6, 0, 0.1, 0],
    [0, 0.1, 0.8, 0, 0, 0.1],
    [0.1, 0, 0, 0.3, 0.6, 0],
    [0, 0.1, 0, 0.1, 0.2, 0.6],
    [0, 0, 0.1, 0, 0.1, 0.8]
])

#print(PU)
#print(PD)
#print(PL)
#print(PR)

P = 1./4 * (PU + PD + PL + PR)

print("P=\n%s" % P)

C = np.array([
    [1, 1, 1, 0],
    [1, 1, 1, 0],
    [1, 0, 1, 1],
    [0, 1, 1, 1],
    [1, 1, 1, 0],
    [0, 1, 1, 1]
])

print("\nC=\n%s" % C)

#1c)


1a)

X: {1, 2, 3, 4, 5, 6}
A: {'D', 'U', 'R', 'L'}

1b)

P=
[[ 0.55   0.225  0.     0.225  0.     0.   ]
 [ 0.225  0.325  0.225  0.     0.225  0.   ]
 [ 0.     0.225  0.55   0.     0.     0.225]
 [ 0.225  0.     0.     0.55   0.225  0.   ]
 [ 0.     0.225  0.     0.225  0.325  0.225]
 [ 0.     0.     0.225  0.     0.225  0.55 ]]

C=
[[1 1 1 0]
 [1 1 1 0]
 [1 0 1 1]
 [0 1 1 1]
 [1 1 1 0]
 [0 1 1 1]]
